services:
  db:
    image: postgres:14 # latest supported by gcp
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: index_app
      POSTGRES_PASSWORD: index_app
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./scripts:/scripts:ro # init and migration scripts
